<?php

$labels = array();

$labels['aliases'] = 'Aliases';
$labels['autoreply_enable'] = "Enable vacation auto-reply";
$labels['autoreply_message'] = 'Auto-reply message';
$labels['autoreply_subject'] = 'Auto-reply subject';
$labels['forward'] = 'Forwarding settings';
$labels['forward_addresses'] = 'Forward mail to (Separate each forward address by a comma or a new line)';
$labels['keep_copy'] = 'Keep a copy of the mail';
$labels['save_settings_fail'] = 'Failed to save plugin settings...';
$labels['save_settings_success'] = 'Save plugin settings successfully.';
$labels['separate_alias'] = 'Separate each alias address by a comma';
$labels['vacation'] = 'Forward and auto-reply';

// button text
$labels['aliasesbutton'] = 'Get aliases';
