<?php
$labels = array();
$labels['aliases'] = '別名(aliases)';
$labels['autoreply'] = "啟用假期自動回信";
$labels['autoreplybutton'] = '儲存';
$labels['autoreplymessage'] = '假期自動回信的內容';
$labels['autoreplysubject'] = '假期自動回信的主旨';
$labels['failed'] = '設定更換失敗！';
$labels['forward'] = '郵件轉送設定';
$labels['forwardingaddresses'] = '轉送郵件到（一行一個郵件地址）';
$labels['keepcopy'] = '在伺服器上保留郵件備份';
$labels['mailforward'] = '郵件轉送';
$labels['separate_alias'] = '以逗點分隔開每一個別名';
$labels['success_changed'] = '設定更換成功！';
$labels['vacation'] = '轉信與假期自動回信';

// Button text
$labels['aliasesbutton'] = '取得別名';
