<?php

$labels = array();

$labels['aliases'] = '別名(aliases)';
$labels['autoreply_enable'] = "啟用假期自動回信";
$labels['autoreply_message'] = '自動回信的內容';
$labels['autoreply_subject'] = '自動回信的主旨';
$labels['forward'] = '郵件轉送設定';
$labels['forward_addresses'] = '轉送郵件到（一行一個郵件地址）';
$labels['keep_copy'] = '在伺服器上保留郵件備份';
$labels['save_settings_fail'] = '設定更換失敗！';
$labels['save_settings_success'] = '設定更換成功！';
$labels['separate_alias'] = '以逗點分隔開每一個別名';
$labels['vacation'] = '轉信與假期自動回信';

// button text
$labels['aliasesbutton'] = '取得別名';
